"""Cria ou recria a tabela relFilDespesasGerais para garantir a estrutura correta.

Revision ID: 3
Revises: 2
Create Date: 2025-08-15 12:33:23.185640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3'
down_revision: Union[str, Sequence[str], None] = '2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    print("--- GARANTindo ESTRUTURA PADRONIZADA PARA a tabela relFilDespesasGerais ---")
    
    # 1. Apaga a tabela existente, se ela existir.
    print("-> Verificando e apagando a versão antiga da tabela (se existir)...")
    #op.execute('DROP TABLE IF EXISTS "relFilDespesasGerais" CASCADE;')

    # 2. Cria a tabela do zero com a estrutura correta e padronizada.
    print("-> Criando a nova tabela 'relFilDespesasGerais' com a estrutura correta...")
    op.create_table('relFilDespesasGerais',
        sa.Column('apartamento_id', sa.Integer(), nullable=False),
        sa.Column('VED', sa.Text(), nullable=True),
        sa.Column('afaturar', sa.Text(), nullable=True),
        sa.Column('agencia', sa.Text(), nullable=True),
        sa.Column('ano', sa.Text(), nullable=True),
        sa.Column('anoMes', sa.Text(), nullable=True),
        sa.Column('banco', sa.Text(), nullable=True),
        sa.Column('box', sa.Text(), nullable=True),
        sa.Column('cadNota', sa.Text(), nullable=True),
        sa.Column('cavalo', sa.Text(), nullable=True),
        sa.Column('cep', sa.Text(), nullable=True),
        sa.Column('chaveNfe', sa.Text(), nullable=True),
        sa.Column('cidadeEmpresas', sa.Text(), nullable=True),
        sa.Column('cidadeFilial', sa.Text(), nullable=True),
        sa.Column('cidadeForn', sa.Text(), nullable=True),
        sa.Column('cnpjCpf', sa.Text(), nullable=True),
        sa.Column('cnpjCpfEmpresas', sa.Text(), nullable=True),
        sa.Column('cnpjCpfFil', sa.Text(), nullable=True),
        sa.Column('cnpjCpfFilial', sa.Text(), nullable=True),
        sa.Column('cnpjCpfForn', sa.Text(), nullable=True),
        sa.Column('codAcertoMotorista', sa.Integer(), nullable=True),
        sa.Column('codAcertoProprietario', sa.Integer(), nullable=True),
        sa.Column('codAdiantamento', sa.Integer(), nullable=True),
        sa.Column('codAgrupador', sa.Integer(), nullable=True),
        sa.Column('codCavalo', sa.Integer(), nullable=True),
        sa.Column('codCfop', sa.Integer(), nullable=True),
        sa.Column('codCfopItem', sa.Integer(), nullable=True),
        sa.Column('codCliente', sa.Integer(), nullable=True),
        sa.Column('codContaContabil', sa.Integer(), nullable=True),
        sa.Column('codEmonitor', sa.Integer(), nullable=True),
        sa.Column('codEmpresas', sa.Integer(), nullable=True),
        sa.Column('codFatura', sa.Integer(), nullable=True),
        sa.Column('codFaturaReceber', sa.Integer(), nullable=True),
        sa.Column('codFilial', sa.Integer(), nullable=True),
        sa.Column('codForn', sa.Integer(), nullable=True),
        sa.Column('codFornProp', sa.Integer(), nullable=True),
        sa.Column('codGrupoD', sa.Integer(), nullable=True),
        sa.Column('codIBGECidC', sa.Integer(), nullable=True),
        sa.Column('codIBGECidF', sa.Integer(), nullable=True),
        sa.Column('codItemD', sa.Integer(), nullable=True),
        sa.Column('codItemDServico', sa.Integer(), nullable=True),
        sa.Column('codItemNota', sa.Integer(), nullable=True),
        sa.Column('codMotNota', sa.Integer(), nullable=True),
        sa.Column('codMotorista', sa.Integer(), nullable=True),
        sa.Column('codNegocio', sa.Integer(), nullable=True),
        sa.Column('codNota', sa.Integer(), nullable=True),
        sa.Column('codProprietario', sa.Integer(), nullable=True),
        sa.Column('codSituacao', sa.Integer(), nullable=True),
        sa.Column('codSuperGrupoD', sa.Integer(), nullable=True),
        sa.Column('codUeItem', sa.Integer(), nullable=True),
        sa.Column('codUnidadeEmbarque', sa.Integer(), nullable=True),
        sa.Column('codVeiculo', sa.Integer(), nullable=True),
        sa.Column('conta', sa.Text(), nullable=True),
        sa.Column('contaContabil', sa.Text(), nullable=True),
        sa.Column('contrato', sa.Text(), nullable=True),
        sa.Column('creditaPisCofins', sa.Text(), nullable=True),
        sa.Column('creditaPisCofinsItem', sa.Text(), nullable=True),
        sa.Column('cstCOFINSItem', sa.Text(), nullable=True),
        sa.Column('cstCOFINSItemD', sa.Text(), nullable=True),
        sa.Column('cstICMSItemD', sa.Text(), nullable=True),
        sa.Column('cstIcmsItem', sa.Text(), nullable=True),
        sa.Column('cstPISItem', sa.Text(), nullable=True),
        sa.Column('cstPISItemD', sa.Text(), nullable=True),
        sa.Column('custo', sa.REAL(), nullable=True),
        sa.Column('custoTotal', sa.REAL(), nullable=True),
        sa.Column('dataAcertoProp', sa.TIMESTAMP(), nullable=True),
        sa.Column('dataControle', sa.TIMESTAMP(), nullable=True),
        sa.Column('dataControleFormat', sa.TIMESTAMP(), nullable=True),
        sa.Column('dataEmissao', sa.TIMESTAMP(), nullable=True),
        sa.Column('dataFim', sa.TIMESTAMP(), nullable=True),
        sa.Column('dataFimOficina', sa.TIMESTAMP(), nullable=True),
        sa.Column('dataINS', sa.TIMESTAMP(), nullable=True),
        sa.Column('dataIniOficina', sa.TIMESTAMP(), nullable=True),
        sa.Column('dataMotorista', sa.TIMESTAMP(), nullable=True),
        sa.Column('dataVenc', sa.TIMESTAMP(), nullable=True),
        sa.Column('dataVencimento', sa.TIMESTAMP(), nullable=True),
        sa.Column('descCodFilial', sa.Text(), nullable=True),
        sa.Column('descCodForn', sa.Text(), nullable=True),
        sa.Column('descCodGrupoDItemNota', sa.Text(), nullable=True),
        sa.Column('descCodItemDItemNota', sa.Text(), nullable=True),
        sa.Column('descCodSuperGrupoDItemNota', sa.Text(), nullable=True),
        sa.Column('descCodUnidadeEmbarque', sa.Text(), nullable=True),
        sa.Column('descGrupoD', sa.Text(), nullable=True),
        sa.Column('descItemD', sa.Text(), nullable=True),
        sa.Column('descNegocio', sa.Text(), nullable=True),
        sa.Column('descSuperGrupoD', sa.Text(), nullable=True),
        sa.Column('descUeItem', sa.Text(), nullable=True),
        sa.Column('descUnidadeEmbarque', sa.Text(), nullable=True),
        sa.Column('desconto', sa.REAL(), nullable=True),
        sa.Column('despesa', sa.Text(), nullable=True),
        sa.Column('endereco', sa.Text(), nullable=True),
        sa.Column('especie', sa.Text(), nullable=True),
        sa.Column('fontCenter', sa.Text(), nullable=True),
        sa.Column('fontLeft', sa.Text(), nullable=True),
        sa.Column('fontRight', sa.Text(), nullable=True),
        sa.Column('frota', sa.Text(), nullable=True),
        sa.Column('garantia', sa.Text(), nullable=True),
        sa.Column('gerenciaEstoque', sa.Text(), nullable=True),
        sa.Column('historico', sa.Text(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=True),
        sa.Column('incluiRateio', sa.Text(), nullable=True),
        sa.Column('inic', sa.Text(), nullable=True),
        sa.Column('inscEst', sa.Text(), nullable=True),
        sa.Column('inscEstForn', sa.Text(), nullable=True),
        sa.Column('investimento', sa.Text(), nullable=True),
        sa.Column('km', sa.REAL(), nullable=True),
        sa.Column('kmAnterior', sa.REAL(), nullable=True),
        sa.Column('kmPrev', sa.REAL(), nullable=True),
        sa.Column('kmRodado', sa.REAL(), nullable=True),
        sa.Column('kmRodadoDec', sa.REAL(), nullable=True),
        sa.Column('liquido', sa.REAL(), nullable=True),
        sa.Column('listItensDespesas', sa.Text(), nullable=True),
        sa.Column('marcaAux', sa.Text(), nullable=True),
        sa.Column('marcaVeic', sa.Text(), nullable=True),
        sa.Column('mediaDesejada', sa.REAL(), nullable=True),
        sa.Column('mediaInversa', sa.Text(), nullable=True),
        sa.Column('mediaKm', sa.REAL(), nullable=True),
        sa.Column('mediaMax', sa.REAL(), nullable=True),
        sa.Column('mediaMin', sa.REAL(), nullable=True),
        sa.Column('modeloAux', sa.Text(), nullable=True),
        sa.Column('modeloVeic', sa.Text(), nullable=True),
        sa.Column('naoEncheuTanque', sa.Text(), nullable=True),
        sa.Column('naoPrevista', sa.Text(), nullable=True),
        sa.Column('ncmItemD', sa.Text(), nullable=True),
        sa.Column('nfFatura', sa.Text(), nullable=True),
        sa.Column('nfeDataHoraRecLote', sa.Text(), nullable=True),
        sa.Column('nome', sa.Text(), nullable=True),
        sa.Column('nomeCidC', sa.Text(), nullable=True),
        sa.Column('nomeCidF', sa.Text(), nullable=True),
        sa.Column('nomeCidFil', sa.Text(), nullable=True),
        sa.Column('nomeEmpresas', sa.Text(), nullable=True),
        sa.Column('nomeFil', sa.Text(), nullable=True),
        sa.Column('nomeFilial', sa.Text(), nullable=True),
        sa.Column('nomeForn', sa.Text(), nullable=True),
        sa.Column('nomeMotorista', sa.Text(), nullable=True),
        sa.Column('numNota', sa.Text(), nullable=True),
        sa.Column('numeroNf', sa.Text(), nullable=True),
        sa.Column('obs', sa.Text(), nullable=True),
        sa.Column('obsItem', sa.Text(), nullable=True),
        sa.Column('obsNota', sa.Text(), nullable=True),
        sa.Column('orderFieldVeiculo', sa.Text(), nullable=True),
        sa.Column('parcela', sa.Text(), nullable=True),
        sa.Column('parcelas', sa.Text(), nullable=True),
        sa.Column('placaCavalo', sa.Text(), nullable=True),
        sa.Column('placaVeiculo', sa.Text(), nullable=True),
        sa.Column('porcAliqIcmsSubsTribItem', sa.REAL(), nullable=True),
        sa.Column('porcIcmsItem', sa.REAL(), nullable=True),
        sa.Column('porcIpiItem', sa.REAL(), nullable=True),
        sa.Column('quantidade', sa.REAL(), nullable=True),
        sa.Column('rateioVeicProp', sa.Text(), nullable=True),
        sa.Column('resumido', sa.Text(), nullable=True),
        sa.Column('serie', sa.Text(), nullable=True),
        sa.Column('serieNf', sa.Text(), nullable=True),
        sa.Column('tempoPrevisto', sa.Text(), nullable=True),
        sa.Column('tipo', sa.Text(), nullable=True),
        sa.Column('tipoConta', sa.Text(), nullable=True),
        sa.Column('tipoNfe', sa.Text(), nullable=True),
        sa.Column('tipoVeiculo', sa.Text(), nullable=True),
        sa.Column('titular', sa.Text(), nullable=True),
        sa.Column('ufCidC', sa.Text(), nullable=True),
        sa.Column('ufCidF', sa.Text(), nullable=True),
        sa.Column('ufCidFil', sa.Text(), nullable=True),
        sa.Column('ufEmpresas', sa.Text(), nullable=True),
        sa.Column('ufFilial', sa.Text(), nullable=True),
        sa.Column('ufForn', sa.Text(), nullable=True),
        sa.Column('unidade', sa.Text(), nullable=True),
        sa.Column('usuarioAut', sa.Text(), nullable=True),
        sa.Column('usuarioINS', sa.Text(), nullable=True),
        sa.Column('valor', sa.REAL(), nullable=True),
        sa.Column('valorAcertoProp', sa.REAL(), nullable=True),
        sa.Column('valorBaseIcmsItem', sa.REAL(), nullable=True),
        sa.Column('valorBaseIpiItem', sa.REAL(), nullable=True),
        sa.Column('valorBaseSubsTribItem', sa.REAL(), nullable=True),
        sa.Column('valorDescontoItem', sa.REAL(), nullable=True),
        sa.Column('valorDespesa', sa.REAL(), nullable=True),
        sa.Column('valorFaturamento', sa.REAL(), nullable=True),
        sa.Column('valorFrete', sa.REAL(), nullable=True),
        sa.Column('valorFreteEmp', sa.REAL(), nullable=True),
        sa.Column('valorFreteMot', sa.REAL(), nullable=True),
        sa.Column('valorIcmsItem', sa.REAL(), nullable=True),
        sa.Column('valorImpSfed', sa.REAL(), nullable=True),
        sa.Column('valorIpiItem', sa.REAL(), nullable=True),
        sa.Column('valorIss', sa.REAL(), nullable=True),
        sa.Column('valorItem', sa.REAL(), nullable=True),
        sa.Column('valorMargem', sa.REAL(), nullable=True),
        sa.Column('valorNota', sa.REAL(), nullable=True),
        sa.Column('valorOutras', sa.REAL(), nullable=True),
        sa.Column('valorPesoSaidaTon', sa.REAL(), nullable=True),
        sa.Column('valorProd', sa.REAL(), nullable=True),
        sa.Column('valorReceitaOp', sa.REAL(), nullable=True),
        sa.Column('valorResultado', sa.REAL(), nullable=True),
        sa.Column('valorResultadoComInv', sa.REAL(), nullable=True),
        sa.Column('valorSeguro', sa.REAL(), nullable=True),
        sa.Column('valorServ', sa.REAL(), nullable=True),
        sa.Column('valorSubsTribItem', sa.REAL(), nullable=True),
        sa.Column('valorUnit', sa.REAL(), nullable=True),
        sa.Column('valorVenc', sa.REAL(), nullable=True),
        sa.Column('veiculoProprio', sa.Text(), nullable=True),
        sa.Column('vlBaseIcms', sa.REAL(), nullable=True),
        sa.Column('vlBaseIcmsSubstTrib', sa.REAL(), nullable=True),
        sa.Column('vlCofinsRet', sa.REAL(), nullable=True),
        sa.Column('vlContabil', sa.REAL(), nullable=True),
        sa.Column('vlCreditoIcms', sa.REAL(), nullable=True),
        sa.Column('vlCsllRet', sa.REAL(), nullable=True),
        sa.Column('vlIcms', sa.REAL(), nullable=True),
        sa.Column('vlIcmsSubstTrib', sa.REAL(), nullable=True),
        sa.Column('vlInssRet', sa.REAL(), nullable=True),
        sa.Column('vlIpi', sa.REAL(), nullable=True),
        sa.Column('vlIrrfRet', sa.REAL(), nullable=True),
        sa.Column('vlPisRet', sa.REAL(), nullable=True)
    )

def downgrade() -> None:
    print("--- REVERTENDO CRIAÇÃO DA TABELA relFilDespesasGerais ---")
    op.drop_table('relFilDespesasGerais')
