# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: meu_projeto_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: meu_projeto_redis

  web:
    build: .
    container_name: meu_projeto_web
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 app:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  worker:
    build: .
    container_name: meu_projeto_worker
    command: python -m rq worker -u ${REDIS_URL} default
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  postgres_data: