version: '3.8'

services:
  # 1. Serviço de Banco de Dados (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: meu_projeto_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Serviço de Cache/Fila (Redis)
  redis:
    image: redis:alpine
    container_name: meu_projeto_redis
    restart: always
    ports:
      - "6379:6379"

  # O SERVIÇO 'migrate' FOI REMOVIDO

  # 3. Serviço da Aplicação Flask/API
  app:
    build: .
    container_name: meu_projeto_web
    restart: on-failure
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://:FQKsme84587@redis:6379
      SECRET_KEY: e8a3f2b1d4c7a0b9e8f1d3a4b6c8d0e1f3a2b4c5d6e7f8a9
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # CORREÇÃO FINAL: Comando Gunicorn mais simples (sem workers count)
    command: gunicorn app:app -b 0.0.0.0:8000
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

  # 4. Serviço RQ Worker (Robôs)
  worker:
    build: .
    container_name: meu_projeto_worker
    restart: on-failure
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://:FQKsme84587@redis:6379
      SECRET_KEY: e8a3f2b1d4c7a0b9e8f1d3a4b6c8d0e1f3a2b4c5d6e7f8a9
    volumes:
      - .:/app
    command: python3 -m rq worker -u redis://redis:6379/0 default
    depends_on:
      app:
        condition: service_started
      redis:
        condition: service_started
      db:
        condition: service_healthy

volumes:
  postgres_data: