services:
  - type: web
    name: python-dashboard
    env: docker
    repo: https://github.com/opalmeida2017-art/dashboard-financeiro-web.git
    autoDeploy: true
    healthCheckPath: /

    # A linha 'startCommand' foi removida aqui

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: financeiro-db
          property: connectionString