services:
  - type: web
    name: python-dashboard
    env: docker
    repo: https://github.com/opalmeida2017-art/dashboard-financeiro-web.git
    autoDeploy: true
    healthCheckPath: /

    startCommand: "python3 -m alembic upgrade head && gunicorn --chdir /app app:app"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: financeiro-db
          property: connectionString

  - type: postgres
    name: financeiro-db
    postgres:
      version: "15"