services:
  # 1. Define o Serviço Web (sua aplicação Python/Flask)
  - type: web
    name: python-dashboard
    env: docker
    repo: https://github.com/opalmeida2017-art/dashboard-financeiro-web.git
    autoDeploy: true
    healthCheckPath: /

    # --- Comando de inicialização que executa as migrações automaticamente ---
    startCommand: "python3 -m alembic upgrade head && gunicorn --chdir /app app:app"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          # CORREÇÃO: Certifique-se de que este nome corresponde ao nome do banco de dados que você criou manualmente.
          name: financeiro-db
          property: connectionString