# Este arquivo descreve toda a infraestrutura da sua aplicação.

services:
  # 1. Define o Serviço Web (sua aplicação Python/Flask)
  - type: web
    name: python-dashboard
    env: docker # Usa o Dockerfile para construir e rodar
    repo: https://github.com/opalmeida2017-art/dashboard-financeiro-web.git # Seu repositório
    autoDeploy: true # Ativa o deploy automático a cada push
    healthCheckPath: /

    # Define as variáveis de ambiente necessárias para o serviço web
    envVars:
      - key: DATABASE_URL
        # Pega a URL de conexão diretamente do banco de dados definido abaixo
      - type: postgres # O tipo correto é 'postgres'
    name: financeiro-db

  # 2. Define o Serviço de Banco de Dados (PostgreSQL)
  - type: pserv # CORREÇÃO: O tipo correto para um banco de dados PostgreSQL no Render é 'pserv'
    name: financeiro-db
    # A imagem do postgres já é gerenciada pelo Render
    # Não precisa de Dockerfile ou repo para o banco de dados.
    # O Render lida com backup, segurança, etc.
    postgres:
      version: "14" # Especificar a versão é uma boa prática
