"""Cria tabela relFilViagensFatCliente

Revision ID: 0002
Revises: 0001
Create Date: 2025-08-13 23:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('relFilViagensFatCliente',
        sa.Column('apartamento_id', sa.Integer(), nullable=False),
        sa.Column('COFINS', sa.REAL(), nullable=True),
        sa.Column('CSLL', sa.REAL(), nullable=True),
        sa.Column('PIS', sa.REAL(), nullable=True),
        sa.Column('acertoSaldo', sa.REAL(), nullable=True),
        sa.Column('adiantamentoEmp2', sa.REAL(), nullable=True),
        sa.Column('adiantamentoEmpresa', sa.REAL(), nullable=True),
        sa.Column('adiantamentoMotorista', sa.REAL(), nullable=True),
        sa.Column('adtoMot2', sa.REAL(), nullable=True),
        sa.Column('agregado', sa.Text(), nullable=True),
        sa.Column('baseISS', sa.REAL(), nullable=True),
        sa.Column('cargaDescarga', sa.REAL(), nullable=True),
        sa.Column('cepCliente', sa.Text(), nullable=True),
        sa.Column('cidCliente', sa.Text(), nullable=True),
        sa.Column('cidDest', sa.Text(), nullable=True),
        sa.Column('cidEmpresas', sa.Text(), nullable=True),
        sa.Column('cidOrig', sa.Text(), nullable=True),
        sa.Column('cidadeClientePrincipal', sa.Text(), nullable=True),
        sa.Column('cidadeDest', sa.Text(), nullable=True),
        sa.Column('cidadeFil', sa.Text(), nullable=True),
        sa.Column('cidadeRem', sa.Text(), nullable=True),
        sa.Column('classificacaoEmbFreteEmp', sa.Text(), nullable=True),
        sa.Column('clientePagaSaldoMotorista', sa.Text(), nullable=True),
        sa.Column('cnpjCpfCliente', sa.Text(), nullable=True),
        sa.Column('cnpjCpfEmpresas', sa.Text(), nullable=True),
        sa.Column('cnpjCpfFil', sa.Text(), nullable=True),
        sa.Column('cnpjCpfProp', sa.Text(), nullable=True),
        sa.Column('codAcertoProprietario', sa.Integer(), nullable=True),
        sa.Column('codCheque', sa.Text(), nullable=True),
        sa.Column('codCliente', sa.Integer(), nullable=True),
        sa.Column('codClientePrincipal', sa.Integer(), nullable=True),
        sa.Column('codDest', sa.Integer(), nullable=True),
        sa.Column('codFatPagAdiant', sa.Integer(), nullable=True),
        sa.Column('codFatPagSaldo', sa.Integer(), nullable=True),
        sa.Column('codFaturaAdiantEmp2', sa.Integer(), nullable=True),
        sa.Column('codFaturaAdiantamento', sa.Integer(), nullable=True),
        sa.Column('codFaturaClassificacao', sa.Integer(), nullable=True),
        sa.Column('codFaturaEstadia', sa.Integer(), nullable=True),
        sa.Column('codFaturaICMS', sa.Integer(), nullable=True),
        sa.Column('codFaturaPedagio', sa.Integer(), nullable=True),
        sa.Column('codFaturaSaldo', sa.Integer(), nullable=True),
        sa.Column('codFaturaSaldoComp', sa.Integer(), nullable=True),
        sa.Column('codFilial', sa.Integer(), nullable=True),
        sa.Column('codFornecedorAdiant', sa.Integer(), nullable=True),
        sa.Column('codFornecedorClassificacao', sa.Integer(), nullable=True),
        sa.Column('codFornecedorICMS', sa.Integer(), nullable=True),
        sa.Column('codFornecedorPedagio', sa.Integer(), nullable=True),
        sa.Column('codFornecedorSaldo', sa.Integer(), nullable=True),
        sa.Column('codManif', sa.Integer(), nullable=True),
        sa.Column('codMercadoria', sa.Integer(), nullable=True),
        sa.Column('codProp', sa.Integer(), nullable=True),
        sa.Column('codRem', sa.Integer(), nullable=True),
        sa.Column('codTipoCliente', sa.Integer(), nullable=True),
        sa.Column('codTransAdiant', sa.Integer(), nullable=True),
        sa.Column('codTransEstadia', sa.Integer(), nullable=True),
        sa.Column('codTransICMS', sa.Integer(), nullable=True),
        sa.Column('codTransPedagio', sa.Integer(), nullable=True),
        sa.Column('codTransSaldo', sa.Integer(), nullable=True),
        sa.Column('codVeiculo', sa.Integer(), nullable=True),
        sa.Column('complementoCliente', sa.Text(), nullable=True),
        sa.Column('contrato', sa.Text(), nullable=True),
        sa.Column('cpfMot', sa.Text(), nullable=True),
        sa.Column('cteDataReciboEnv', sa.Text(), nullable=True),
        sa.Column('cteStatus', sa.Text(), nullable=True),
        sa.Column('cteStatusDesc', sa.Text(), nullable=True),
        sa.Column('dataChegouSaldo', sa.Text(), nullable=True),
        sa.Column('dataEmissao', sa.Text(), nullable=True),
        sa.Column('dataEncerramento', sa.Text(), nullable=True),
        sa.Column('dataFatPagAdiant', sa.Text(), nullable=True),
        sa.Column('dataFatPagSaldo', sa.Text(), nullable=True),
        sa.Column('dataFatSaldo', sa.Text(), nullable=True),
        sa.Column('dataINS', sa.Text(), nullable=True),
        sa.Column('dataNascimentoMot', sa.Text(), nullable=True),
        sa.Column('dataPagtoDuplicatas', sa.Text(), nullable=True),
        sa.Column('dataPrevDescarga', sa.Text(), nullable=True),
        sa.Column('dataVencAdiant', sa.Text(), nullable=True),
        sa.Column('dataVencSaldo', sa.Text(), nullable=True),
        sa.Column('dataViagemMotorista', sa.Text(), nullable=True),
        sa.Column('descCSLLSaldoEmp', sa.REAL(), nullable=True),
        sa.Column('descCofinsSaldoEmp', sa.REAL(), nullable=True),
        sa.Column('descColeta', sa.REAL(), nullable=True),
        sa.Column('descDifFrete', sa.REAL(), nullable=True),
        sa.Column('descEntrega', sa.REAL(), nullable=True),
        sa.Column('descIRRFSaldoEmp', sa.REAL(), nullable=True),
        sa.Column('descPISSaldoEmp', sa.REAL(), nullable=True),
        sa.Column('descPedagioBaseMot', sa.REAL(), nullable=True),
        sa.Column('descQuebraSaldoEmp', sa.Text(), nullable=True),
        sa.Column('descSeguro2Saldo', sa.REAL(), nullable=True),
        sa.Column('descSeguro2SaldoMot', sa.REAL(), nullable=True),
        sa.Column('descSeguroSaldo', sa.REAL(), nullable=True),
        sa.Column('descSeguroSaldoMot', sa.REAL(), nullable=True),
        sa.Column('descSestSenatSaldoEmp', sa.REAL(), nullable=True),
        sa.Column('descontaICMSSaldoEmpresa', sa.Text(), nullable=True),
        sa.Column('descontaINSSSaldo', sa.Text(), nullable=True),
        sa.Column('descontaINSSSaldoMot', sa.Text(), nullable=True),
        sa.Column('descontaISSSaldoEmp', sa.Text(), nullable=True),
        sa.Column('descricaoMercadoria', sa.Text(), nullable=True),
        sa.Column('despesaExtra', sa.REAL(), nullable=True),
        sa.Column('enderecoCliente', sa.Text(), nullable=True),
        sa.Column('enderecoEmpresas', sa.Text(), nullable=True),
        sa.Column('enderecoFil', sa.Text(), nullable=True),
        sa.Column('estadiaEmbutidaFrete', sa.Text(), nullable=True),
        sa.Column('fEmp', sa.REAL(), nullable=True),
        sa.Column('faturaICMSFinal', sa.REAL(), nullable=True),
        sa.Column('faturaPesoChegada', sa.REAL(), nullable=True),
        sa.Column('faturamento', sa.REAL(), nullable=True),
        sa.Column('faxEmpresas', sa.Text(), nullable=True),
        sa.Column('faxFil', sa.Text(), nullable=True),
        sa.Column('foneCliente', sa.Text(), nullable=True),
        sa.Column('foneEmpresas', sa.Text(), nullable=True),
        sa.Column('foneFil', sa.Text(), nullable=True),
        sa.Column('freteCombinado', sa.REAL(), nullable=True),
        sa.Column('freteEmpresa', sa.REAL(), nullable=True),
        sa.Column('freteEmpresaComp', sa.REAL(), nullable=True),
        sa.Column('freteEmpresaSai', sa.REAL(), nullable=True),
        sa.Column('freteMotorista', sa.REAL(), nullable=True),
        sa.Column('freteMotoristaSai', sa.REAL(), nullable=True),
        sa.Column('historico1FatSaldo', sa.Text(), nullable=True),
        sa.Column('historico2FatSaldo', sa.Text(), nullable=True),
        sa.Column('historicoFatSaldo', sa.Text(), nullable=True),
        sa.Column('horaFimDescarga', sa.Text(), nullable=True),
        sa.Column('icmsEmbutido', sa.Text(), nullable=True),
        sa.Column('inscEstCliente', sa.Text(), nullable=True),
        sa.Column('issEmbutido', sa.Text(), nullable=True),
        sa.Column('kmFim', sa.REAL(), nullable=True),
        sa.Column('kmIni', sa.REAL(), nullable=True),
        sa.Column('kmParc', sa.REAL(), nullable=True),
        sa.Column('kmRodado', sa.REAL(), nullable=True),
        sa.Column('liberadoOrdServ', sa.Text(), nullable=True),
        sa.Column('nomeCliente', sa.Text(), nullable=True),
        sa.Column('nomeClientePrincipal', sa.Text(), nullable=True),
        sa.Column('nomeDest', sa.Text(), nullable=True),
        sa.Column('nomeEmpresas', sa.Text(), nullable=True),
        sa.Column('nomeFilial', sa.Text(), nullable=True),
        sa.Column('nomeFornSaldo', sa.Text(), nullable=True),
        sa.Column('nomeMot', sa.Text(), nullable=True),
        sa.Column('nomeProp', sa.Text(), nullable=True),
        sa.Column('nomeRem', sa.Text(), nullable=True),
        sa.Column('numConhec', sa.Integer(), nullable=True),
        sa.Column('numNF', sa.Text(), nullable=True),
        sa.Column('numPedido', sa.Text(), nullable=True),
        sa.Column('numero', sa.Text(), nullable=True),
        sa.Column('numeroClassificacao', sa.Text(), nullable=True),
        sa.Column('numeroICMS', sa.Text(), nullable=True),
        sa.Column('numeroProgramacao', sa.Text(), nullable=True),
        sa.Column('obsFatSaldo', sa.Text(), nullable=True),
        sa.Column('outrosDescontos', sa.REAL(), nullable=True),
        sa.Column('outrosDescontosMot', sa.REAL(), nullable=True),
        sa.Column('outrosDescontosMot2', sa.REAL(), nullable=True),
        sa.Column('pagaICMS', sa.Text(), nullable=True),
        sa.Column('pedagioEmbutidoFrete', sa.Text(), nullable=True),
        sa.Column('pedidoFrete', sa.Text(), nullable=True),
        sa.Column('percRedVLICMS', sa.REAL(), nullable=True),
        sa.Column('permiteFaturar', sa.Text(), nullable=True),
        sa.Column('permitePagarSaldoFrota', sa.Text(), nullable=True),
        sa.Column('pesoChegada', sa.REAL(), nullable=True),
        sa.Column('pesoSaida', sa.REAL(), nullable=True),
        sa.Column('pesoSaidaMotorista', sa.REAL(), nullable=True),
        sa.Column('placa', sa.Text(), nullable=True),
        sa.Column('precoTonEmpresa', sa.REAL(), nullable=True),
        sa.Column('precoTonMotorista', sa.REAL(), nullable=True),
        sa.Column('premioSeguro', sa.REAL(), nullable=True),
        sa.Column('premioSeguro2', sa.REAL(), nullable=True),
        sa.Column('quantMercadoria', sa.REAL(), nullable=True),
        sa.Column('quantidadeQuebra', sa.REAL(), nullable=True),
        sa.Column('quebraSegurada', sa.Text(), nullable=True),
        sa.Column('saldoEmp', sa.REAL(), nullable=True),
        sa.Column('saldoMotorista', sa.REAL(), nullable=True),
        sa.Column('somaFreteEmpresaComICMS', sa.REAL(), nullable=True),
        sa.Column('somarISSFatSaldo', sa.Text(), nullable=True),
        sa.Column('taxaAdiantEmpresa', sa.REAL(), nullable=True),
        sa.Column('tipoCte', sa.Text(), nullable=True),
        sa.Column('tipoFat', sa.Text(), nullable=True),
        sa.Column('tipoFrete', sa.Text(), nullable=True),
        sa.Column('tributaImpostos', sa.Text(), nullable=True),
        sa.Column('ufCidCliente', sa.Text(), nullable=True),
        sa.Column('ufCidDest', sa.Text(), nullable=True),
        sa.Column('ufCidFil', sa.Text(), nullable=True),
        sa.Column('ufCidRem', sa.Text(), nullable=True),
        sa.Column('ufClientePrincipal', sa.Text(), nullable=True),
        sa.Column('ufDest', sa.Text(), nullable=True),
        sa.Column('ufOrig', sa.Text(), nullable=True),
        sa.Column('vPercARet', sa.REAL(), nullable=True),
        sa.Column('valorAbonoQuebra', sa.REAL(), nullable=True),
        sa.Column('valorBalsa', sa.REAL(), nullable=True),
        sa.Column('valorClassificacao', sa.REAL(), nullable=True),
        sa.Column('valorEstadia', sa.REAL(), nullable=True),
        sa.Column('valorFreteEmpresaICMS', sa.REAL(), nullable=True),
        sa.Column('valorFreteFiscal', sa.REAL(), nullable=True),
        sa.Column('valorICMS', sa.REAL(), nullable=True),
        sa.Column('valorICMSNaoEmb', sa.REAL(), nullable=True),
        sa.Column('valorINSS', sa.REAL(), nullable=True),
        sa.Column('valorINSSEmpresa', sa.REAL(), nullable=True),
        sa.Column('valorIRRF', sa.REAL(), nullable=True),
        sa.Column('valorISS', sa.REAL(), nullable=True),
        sa.Column('valorPedagio', sa.REAL(), nullable=True),
        sa.Column('valorQuebra', sa.REAL(), nullable=True),
        sa.Column('valorRastreamento', sa.REAL(), nullable=True),
        sa.Column('valorSestSenat', sa.REAL(), nullable=True),
        sa.Column('valorTotalDPsPagoViagem', sa.REAL(), nullable=True),
        sa.Column('veiculoProprio', sa.Text(), nullable=True),
        sa.Column('vlARec', sa.REAL(), nullable=True),
        sa.Column('vlAfat', sa.REAL(), nullable=True),
        sa.Column('vlCOFINS', sa.REAL(), nullable=True),
        sa.Column('vlCSLL', sa.REAL(), nullable=True),
        sa.Column('vlFaturado', sa.REAL(), nullable=True),
        sa.Column('vlPIS', sa.REAL(), nullable=True),
        sa.Column('vlRec', sa.REAL(), nullable=True)
    )


def downgrade() -> None:
    op.drop_table('relFilViagensFatCliente')

