"""Cria tabela relFilViagensCliente

Revision ID: 0003
Revises: 0002
Create Date: 2025-08-13 23:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('relFilViagensCliente',
        sa.Column('apartamento_id', sa.Integer(), nullable=False),
        sa.Column('acertoICMS', sa.Text(), nullable=True),
        sa.Column('acertoSaldo', sa.REAL(), nullable=True),
        sa.Column('adValor', sa.REAL(), nullable=True),
        sa.Column('adiantamentoMotorista', sa.REAL(), nullable=True),
        sa.Column('adtoMot2', sa.REAL(), nullable=True),
        sa.Column('aliquotaCofins', sa.REAL(), nullable=True),
        sa.Column('aliquotaIss', sa.REAL(), nullable=True),
        sa.Column('aliquotaPis', sa.REAL(), nullable=True),
        sa.Column('arqXMLAss', sa.Text(), nullable=True),
        sa.Column('baseICMS', sa.REAL(), nullable=True),
        sa.Column('baseICMSDireta', sa.REAL(), nullable=True),
        sa.Column('baseImpostos', sa.REAL(), nullable=True),
        sa.Column('baseIss', sa.REAL(), nullable=True),
        sa.Column('cancelado', sa.Text(), nullable=True),
        sa.Column('cargaDescarga', sa.REAL(), nullable=True),
        sa.Column('cartaFrete', sa.Text(), nullable=True),
        sa.Column('celularMotorista', sa.Text(), nullable=True),
        sa.Column('celularProp', sa.Text(), nullable=True),
        sa.Column('chaveNF', sa.Text(), nullable=True),
        sa.Column('checkList', sa.Text(), nullable=True),
        sa.Column('cidDestinoFormat', sa.Text(), nullable=True),
        sa.Column('cidOrigemFormat', sa.Text(), nullable=True),
        sa.Column('cnhMotorista', sa.Text(), nullable=True),
        sa.Column('cnpjCpfCliente', sa.Text(), nullable=True),
        sa.Column('cnpjCpfDest', sa.Text(), nullable=True),
        sa.Column('cnpjCpfEmpresas', sa.Text(), nullable=True),
        sa.Column('cnpjCpfFilial', sa.Text(), nullable=True),
        sa.Column('cnpjCpfProp', sa.Text(), nullable=True),
        sa.Column('cnpjCpfRemet', sa.Text(), nullable=True),
        sa.Column('cnpjUnidadeEmb', sa.Text(), nullable=True),
        sa.Column('codClDest', sa.Integer(), nullable=True),
        sa.Column('codClRemet', sa.Integer(), nullable=True),
        sa.Column('codCliente', sa.Integer(), nullable=True),
        sa.Column('codColetaEntregaAg', sa.Integer(), nullable=True),
        sa.Column('codEmpresas', sa.Integer(), nullable=True),
        sa.Column('codFaturaSaldo', sa.Integer(), nullable=True),
        sa.Column('codFilial', sa.Integer(), nullable=True),
        sa.Column('codMercadoria', sa.Integer(), nullable=True),
        sa.Column('codOrdemCar', sa.Integer(), nullable=True),
        sa.Column('codProp', sa.Integer(), nullable=True),
        sa.Column('codRota', sa.Integer(), nullable=True),
        sa.Column('codServicoNfs', sa.Integer(), nullable=True),
        sa.Column('codUnidadeEmb', sa.Integer(), nullable=True),
        sa.Column('comissao', sa.REAL(), nullable=True),
        sa.Column('cpfMotorista', sa.Text(), nullable=True),
        sa.Column('cteChave', sa.Text(), nullable=True),
        sa.Column('cteDataReciboEnv', sa.Text(), nullable=True),
        sa.Column('cteFusoHorarioAutor', sa.Text(), nullable=True),
        sa.Column('cteProt', sa.Text(), nullable=True),
        sa.Column('cteStatus', sa.Text(), nullable=True),
        sa.Column('dataALT', sa.Text(), nullable=True),
        sa.Column('dataEmissao', sa.Text(), nullable=True),
        sa.Column('dataEmissaoComHora', sa.Text(), nullable=True),
        sa.Column('dataINS', sa.Text(), nullable=True),
        sa.Column('dataNascimentoProp', sa.Text(), nullable=True),
        sa.Column('dataPrevDescarga', sa.Text(), nullable=True),
        sa.Column('dataPrevEntrega', sa.Text(), nullable=True),
        sa.Column('dataViagemMotorista', sa.Text(), nullable=True),
        sa.Column('descAg', sa.Text(), nullable=True),
        sa.Column('descEntrega', sa.Text(), nullable=True),
        sa.Column('descTipoCte', sa.Text(), nullable=True),
        sa.Column('descontaICMSSaldoEmpresa', sa.Text(), nullable=True),
        sa.Column('descontaINSSSaldoMot', sa.Text(), nullable=True),
        sa.Column('descricaoEspecieMerc', sa.Text(), nullable=True),
        sa.Column('descricaoMercadoria', sa.Text(), nullable=True),
        sa.Column('despesaExtra', sa.REAL(), nullable=True),
        sa.Column('despesasadicionais', sa.REAL(), nullable=True),
        sa.Column('embarcadorNome', sa.Text(), nullable=True),
        sa.Column('envioLote', sa.Text(), nullable=True),
        sa.Column('estadiaEmbutidaFrete', sa.Text(), nullable=True),
        sa.Column('fTotalPrest', sa.REAL(), nullable=True),
        sa.Column('faturaICMSFinal', sa.REAL(), nullable=True),
        sa.Column('faturaPesoChegada', sa.REAL(), nullable=True),
        sa.Column('foneMotorista', sa.Text(), nullable=True),
        sa.Column('foneProp', sa.Text(), nullable=True),
        sa.Column('freteEmpresa', sa.REAL(), nullable=True),
        sa.Column('freteEmpresaSai', sa.REAL(), nullable=True),
        sa.Column('freteMotorista', sa.REAL(), nullable=True),
        sa.Column('freteMotoristaSai', sa.REAL(), nullable=True),
        sa.Column('fretePago', sa.Text(), nullable=True),
        sa.Column('horaFimDescarga', sa.Text(), nullable=True),
        sa.Column('icmsEmbutido', sa.Text(), nullable=True),
        sa.Column('inscricaoEstadualFilial', sa.Text(), nullable=True),
        sa.Column('margemFrete', sa.REAL(), nullable=True),
        sa.Column('margemFretePerc', sa.REAL(), nullable=True),
        sa.Column('modelo', sa.Text(), nullable=True),
        sa.Column('natureza', sa.Text(), nullable=True),
        sa.Column('nfseProt', sa.Text(), nullable=True),
        sa.Column('nfseStatus', sa.Text(), nullable=True),
        sa.Column('nfseStatusDesc', sa.Text(), nullable=True),
        sa.Column('nomeCidCliente', sa.Text(), nullable=True),
        sa.Column('nomeCidDestino', sa.Text(), nullable=True),
        sa.Column('nomeCidOrigem', sa.Text(), nullable=True),
        sa.Column('nomeClDest', sa.Text(), nullable=True),
        sa.Column('nomeClRemet', sa.Text(), nullable=True),
        sa.Column('nomeCliente', sa.Text(), nullable=True),
        sa.Column('nomeEmpresas', sa.Text(), nullable=True),
        sa.Column('nomeFilial', sa.Text(), nullable=True),
        sa.Column('nomeMotorista', sa.Text(), nullable=True),
        sa.Column('nomeProp', sa.Text(), nullable=True),
        sa.Column('nomeUnidEmb', sa.Text(), nullable=True),
        sa.Column('numConhec', sa.Integer(), nullable=True),
        sa.Column('numConhecColEntrega', sa.Text(), nullable=True),
        sa.Column('numNF', sa.Text(), nullable=True),
        sa.Column('numNotaNF', sa.Text(), nullable=True),
        sa.Column('numPedido', sa.Text(), nullable=True),
        sa.Column('numero', sa.Text(), nullable=True),
        sa.Column('numeroApolice', sa.Text(), nullable=True),
        sa.Column('numeroColEntrega', sa.Text(), nullable=True),
        sa.Column('obs', sa.Text(), nullable=True),
        sa.Column('obsFaturaPeso', sa.Text(), nullable=True),
        sa.Column('obsFiscal', sa.Text(), nullable=True),
        sa.Column('outrosDescontos', sa.REAL(), nullable=True),
        sa.Column('outrosDescontosMot', sa.REAL(), nullable=True),
        sa.Column('outrosDescontosMot2', sa.REAL(), nullable=True),
        sa.Column('pagaICMS', sa.Text(), nullable=True),
        sa.Column('pagaISS', sa.Text(), nullable=True),
        sa.Column('pagar', sa.Text(), nullable=True),
        sa.Column('pedagioEmbFreteMot', sa.Text(), nullable=True),
        sa.Column('pedagioEmbutido', sa.Text(), nullable=True),
        sa.Column('pedagioEmbutidoFrete', sa.Text(), nullable=True),
        sa.Column('pedidoCliente2', sa.Text(), nullable=True),
        sa.Column('pedidoFrete', sa.Text(), nullable=True),
        sa.Column('pedidoTransf', sa.Text(), nullable=True),
        sa.Column('percRedVLICMS', sa.REAL(), nullable=True),
        sa.Column('permiteFaturar', sa.Text(), nullable=True),
        sa.Column('permitePagarSaldoFrota', sa.Text(), nullable=True),
        sa.Column('pesoChegada', sa.REAL(), nullable=True),
        sa.Column('pesoSaida', sa.REAL(), nullable=True),
        sa.Column('pesoSaidaMotorista', sa.REAL(), nullable=True),
        sa.Column('pisProp', sa.Text(), nullable=True),
        sa.Column('placaVeiculo', sa.Text(), nullable=True),
        sa.Column('porcICMS', sa.REAL(), nullable=True),
        sa.Column('precoKgMercQuebra', sa.REAL(), nullable=True),
        sa.Column('precoMercadoria', sa.REAL(), nullable=True),
        sa.Column('precoTonEmpresa', sa.REAL(), nullable=True),
        sa.Column('precoTonFiscal', sa.REAL(), nullable=True),
        sa.Column('precoTonMotorista', sa.REAL(), nullable=True),
        sa.Column('premioSeguro', sa.REAL(), nullable=True),
        sa.Column('premioSeguro2', sa.REAL(), nullable=True),
        sa.Column('quantMercadoria', sa.REAL(), nullable=True),
        sa.Column('quantidadeQuebra', sa.REAL(), nullable=True),
        sa.Column('quebraSegurada', sa.Text(), nullable=True),
        sa.Column('quebraTotal', sa.REAL(), nullable=True),
        sa.Column('rgMotorista', sa.Text(), nullable=True),
        sa.Column('sacaCarRPapel', sa.Text(), nullable=True),
        sa.Column('saldoMotorista', sa.REAL(), nullable=True),
        sa.Column('secCatEmbutidoFrete', sa.Text(), nullable=True),
        sa.Column('serieCte', sa.Text(), nullable=True),
        sa.Column('serieNF', sa.Text(), nullable=True),
        sa.Column('taxaQuebra', sa.REAL(), nullable=True),
        sa.Column('tempo', sa.Text(), nullable=True),
        sa.Column('tempoAtraso', sa.Text(), nullable=True),
        sa.Column('tempoPrev', sa.Text(), nullable=True),
        sa.Column('tempoTransp', sa.Text(), nullable=True),
        sa.Column('tipoDesconto', sa.Text(), nullable=True),
        sa.Column('tipoFrete', sa.Text(), nullable=True),
        sa.Column('tipoTolerancia', sa.Text(), nullable=True),
        sa.Column('tipoTributacao', sa.Text(), nullable=True),
        sa.Column('toleranciaPesoCheg', sa.REAL(), nullable=True),
        sa.Column('tributaImpostos', sa.Text(), nullable=True),
        sa.Column('ufCliente', sa.Text(), nullable=True),
        sa.Column('ufDestino', sa.Text(), nullable=True),
        sa.Column('ufOrigem', sa.Text(), nullable=True),
        sa.Column('usuarioALT', sa.Text(), nullable=True),
        sa.Column('usuarioINS', sa.Text(), nullable=True),
        sa.Column('valorAbonoQuebra', sa.REAL(), nullable=True),
        sa.Column('valorBalsa', sa.REAL(), nullable=True),
        sa.Column('valorClassificacao', sa.REAL(), nullable=True),
        sa.Column('valorCofins', sa.REAL(), nullable=True),
        sa.Column('valorEstadia', sa.REAL(), nullable=True),
        sa.Column('valorFreteFiscal', sa.REAL(), nullable=True),
        sa.Column('valorICMS', sa.REAL(), nullable=True),
        sa.Column('valorINSS', sa.REAL(), nullable=True),
        sa.Column('valorIRRF', sa.REAL(), nullable=True),
        sa.Column('valorIss', sa.REAL(), nullable=True),
        sa.Column('valorMercadoria', sa.REAL(), nullable=True),
        sa.Column('valorPedagio', sa.REAL(), nullable=True),
        sa.Column('valorPis', sa.REAL(), nullable=True),
        sa.Column('valorQuebra', sa.REAL(), nullable=True),
        sa.Column('valorSeguro', sa.REAL(), nullable=True),
        sa.Column('valorSeguro2', sa.REAL(), nullable=True),
        sa.Column('valorSestSenat', sa.REAL(), nullable=True),
        sa.Column('valorTotalnf', sa.REAL(), nullable=True),
        sa.Column('versaoCte', sa.Text(), nullable=True),
        sa.Column('vlTotalPrestacaoDacte', sa.REAL(), nullable=True),
        sa.Column('adiantamentoEmpresa', sa.REAL(), nullable=True),
        sa.Column('cidadeClientePrincipal', sa.Text(), nullable=True),
        sa.Column('dataVencSaldo', sa.Text(), nullable=True),
        sa.Column('descSeguroSaldoMot', sa.REAL(), nullable=True),
        sa.Column('freteEmpresaComp', sa.REAL(), nullable=True),
        sa.Column('numeroConhecimento', sa.Integer(), nullable=True),
        sa.Column('saldoEmp', sa.REAL(), nullable=True),
        sa.Column('vlIcms', sa.REAL(), nullable=True)
    )


def downgrade() -> None:
    op.drop_table('relFilViagensCliente')

